services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
