name: test

on:
    pull_request:
        branches: ["master"]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run Docker
              run: docker compose up -d --build

            - name: Instala dependências
              run: docker compose exec php composer install

            - name: Roda os testes
              run: docker compose exec php vendor/bin/phpunit tests/ 